### Spam Ham Classification using BOW

In [1]:
import pandas as pd

In [2]:
messages = pd.read_csv('../Bag of Words/SMSSpamCollection.csv')

In [3]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5569  spam  This is the 2nd time we have tried 2 contact u...
5570   ham               Will ü b going to esplanade fr home?
5571   ham  Pity, * was in mood for that. So...any other s...
5572   ham  The guy did some bitching but I acted like i'd...
5573   ham                         Rofl. Its true to its name

[5574 rows x 2 columns]

In [4]:
# data cleaning

import re
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
ps = PorterStemmer()

In [5]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\om_da\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
corpus = []
for i in range(len(messages)):
    # remove special characters
    review = re.sub('^[a-zA-Z]', ' ', messages['message'][i])
    # lower all the case
    review = review.lower()
    # convert it to list of words
    review = review.split()
    # if not present in stopwords, apply stemming to it
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
corpus

['jurong point, crazy.. avail bugi n great world la e buffet... cine got amor wat...',
 'k lar... joke wif u oni...',
 "ree entri 2 wkli comp win fa cup final tkt 21st may 2005. text fa 87121 receiv entri question(std txt rate)t&c' appli 08452810075over18'",
 'dun say earli hor... u c alreadi say...',
 'ah think goe usf, live around though',
 "reemsg hey darl 3 week' word back! like fun still? tb ok! xxx std chg send, £1.50 rcv",
 'ven brother like speak me. treat like aid patent.',
 "per request 'mell mell (oru minnaminungint nurungu vettam)' set callertun callers. press *9 copi friend callertun",
 'inner!! valu network custom select receivea £900 prize reward! claim call 09061701461. claim code kl341. valid 12 hour only.',
 'ad mobil 11 month more? u r entitl updat latest colour mobil camera free! call mobil updat co free 08002986030',
 "'m gonna home soon want talk stuff anymor tonight, k? cri enough today.",
 'ix chanc win cash! 100 20,000 pound txt> csh11 send 87575. cost 150p/day, 6days, 16+ tsandc appli repli hl 4 info',
 'rgent! 1 week free membership £100,000 prize jackpot! txt word: claim no: 81010 t&c www.dbuk.net lccltd pobox 4403ldnw1a7rw18',
 "'ve search right word thank breather. promis wont take help grant fulfil promise. wonder bless times.",
 'date sunday will!!',
 'xxmobilemovieclub: use credit, click wap link next txt messag click here>> http://wap. xxxmobilemovieclub.com?n=qjkgighjjgcbl',
 "h k...i'm watch here:)",
 'h u rememb 2 spell name... ye did. v naughti make v wet.',
 'ine that\x92 way u feel. that\x92 way gota b',
 'ngland v macedonia - dont miss goals/team news. txt ur nation team 87077 eg england 87077 try:wales, scotland 4txt/ú1.20 poboxox36504w45wq 16+',
 'serious spell name?',
 '‘m go tri 2 month ha ha joke',
 'ü pay first lar... da stock comin...',
 'ft finish lunch go str lor. ard 3 smth lor. u finish ur lunch already?',
 'fffffffff. alright way meet sooner?',
 'ust forc eat slice. realli hungri tho. sucks. mark get worried. know sick turn pizza. lol',
 'ol alway convincing.',
 "id catch bu ? fri egg ? make tea? eat mom' left dinner ? feel love ?",
 "'m back &amp; pack car now, let know there' room",
 'hhh. work. vagu rememb that! feel like? lol',
 "ait that' still clear, sure sarcast that' x want live us",
 'eah got 2 v apologetic. n fallen actin like spoilt child got caught that. till 2! go there! badli cheers. you?',
 'tell anyth you.',
 'fear faint housework did? quick cuppa',
 'hank subscript rington uk mobil charg £5/month pleas confirm repli ye no. repli charg',
 'up... ok go home look time msg ü again... xuhui go learn 2nd may lesson 8am',
 "ops, let know roommate' done",
 'see letter b car',
 'nyth lor... u decide...',
 "ello! how' saturday go? text see decid anyth tomo. tri invit anything!",
 'ls go ahead watts. want sure. great weekend. abiola',
 'id forget tell ? want , need you, crave ... ... love sweet arabian steed ... mmmmmm ... yummi',
 '07732584351 - rodger burn - msg = tri call repli sm free nokia mobil + free camcorder. pleas call 08000930705 deliveri tomorrow',
 'ho seeing?',
 'reat! hope like man well endowed. &lt;#&gt; inches...',
 'calls..messages..miss call',
 "idn't get hep b immunis nigeria.",
 'air enough, anyth go on?',
 "eah hopefully, tyler can't could mayb ask around bit",
 'know stubborn am. even want go hospital. kept tell mark weak sucker. hospit weak suckers.',
 'hat think me. first time saw class.',
 'gram usual run like &lt;#&gt; , half eighth smarter though get almost whole second gram &lt;#&gt;',
 'fyi x ride earli tomorrow morn crash place tonight',
 'ow. never realiz embarass accomodations. thought like it, sinc best could alway seem happi "the cave". sorri give. sorri offered. sorri room embarassing.',
 'ms. ac sptv: new jersey devil detroit red wing play ice hockey. correct incorrect? end? repli end sptv',
 'know mallika sherawat yesterday? find @ &lt;url&gt;',
 'ongrats! 1 year special cinema pass 2 yours. call 09061209465 now! c suprman v, matrix3, starwars3, etc 4 free! bx420-ip4-5we. 150pm. dont miss out!',
 'orry, call later meeting.',
 'ell reach',
 'es..gauti sehwag odi series.',
 "gonna pick $1 burger way home. can't even move. pain kill me.",
 'ha ha good joke. girl situat seekers.',
 'ts part check iq',
 'orri roommat took forever, ok come now?',
 'k lar doubl check wif da hair dresser alreadi said wun cut v short. said cut look nice.',
 'valu customer, pleas advis follow recent review mob no. award £1500 bonu prize, call 09066364589',
 'oday "song dedic day.." song u dedic me? send ur valuabl frnd first rpli me...',
 'rgent ur award complimentari trip eurodisinc trav, aco&entry41 £1000. claim txt di 87121 18+6*£1.50(morefrmmob. shracomorsglsuplt)10, ls1 3aj',
 'id hear new "divorc barbie"? come ken\' stuff!',
 'plane give month end.',
 'ah lucki man... save money... hee...',
 'inish class you.',
 'babe im home wanna something? xx',
 '..k:)where you?how performed?',
 'call now...',
 'wait machan. call free.',
 'hat cool. gentleman treat digniti respect.',
 'like peopl much:) shi pa.',
 'oe oper &lt;#&gt;',
 "ts here. still look job. much ta' earn there.",
 'orry, call later',
 '. call ah?',
 'k way home hi hi',
 'ou place man',
 'next stop.',
 'call later, network. urgnt, sm me.',
 'real u get yo? need 2 ticket one jacket done. alreadi use multis.',
 'es start send request make pain came back back bed. doubl coin factori too. gotta cash nitros.',
 "'m realli still tonight babe",
 'la kano.,il download, come wen ur free..',
 'eah do! don‘t stand close tho- you‘ll catch something!',
 'orri pain. ok meet anoth night? spent late afternoon casualti mean done stuff42moro includ time sheet that. sorry.',
 'mile pleasur smile pain smile troubl pour like rain smile sum1 hurt u smile becoz someon still love see u smiling!!',
 'leas call custom servic repres 0800 169 6031 10am-9pm guarante £1000 cash £5000 prize!',
 'avent plan buy later. check alreadi lido got 530 show e afternoon. u finish work already?',
 'free rington wait collected. simpli text password "mix" 85069 verify. get usher britney. fml, po box 5249, mk17 92h. 450ppw 16',
 'atch telugu movie..wat abt u?',
 'see. finish load loan pay',
 'i. wk ok - hol now! ye bit run. forgot hairdress appoint four need get home n shower beforehand. caus prob u?"',
 'see cup coffe anim',
 'leas text anymore. noth els say.',
 'kay name ur price long legal! wen pick up? u ave x am xx',
 "'m still look car buy. gone 4the drive test yet.",
 "per request 'mell mell (oru minnaminungint nurungu vettam)' set callertun callers. press *9 copi friend callertun",
 'ow. right! mean that. guess gave boston men chang search locat nyc, someth changed. cuz signin page still say boston.',
 'mma life vava umma love lot dear',
 'hank lot wish birthday. thank make birthday truli memorable.',
 'ight, hit get cash',
 'ow would ip address test consid comput minecraft server',
 'know! grumpi old people. mom like better lying. alway one play jokes...',
 'ont worry. guess busy.',
 'hat plural noun research?',
 'o dinner.msg after.',
 "'m ok wif co like 2 tri new things. scare u dun like mah. co u said loud.",
 'ent! tri contact you. last weekend draw show £1000 prize guaranteed. call 09064012160. claim code k52. valid 12hr only. 150ppm',
 'a, ur openin sentenc formal... anyway, fine too, juz tt eatin much n puttin weight...haha... anythin special happened?',
 "enter cabin pa said, '' happi b'day boss !!''. felt special. askd 4 lunch. lunch invit apartment. went there.",
 'ou winner u special select 2 receiv £1000 4* holiday (flight inc) speak live oper 2 claim 0871277810910p/min (18+)',
 'oodo! ye must speak friday - egg-potato ratio tortilla needed!',
 'mm...mi uncl inform pay school directly. pl buy food.',
 'rivate! 2004 account statement 07742676969 show 786 unredeem bonu points. claim call 08719180248 identifi code: 45239 expir',
 'rgent! mobil no. award £2000 bonu caller prize 5/9/03 final tri contact u! call landlin 09064019788 box42wr29c, 150ppm',
 'ere new address -apples&pairs&al malarki',
 'oday voda number end 7548 select receiv $350 award. match pleas call 08712300220 quot claim code 4041 standard rate app',
 'go sao mu today. done 12',
 "ü predict wat time ü'll finish buying?",
 'ood stuff, do.',
 'ust know,yetund sent money yet. sent text bother sending. over, dont involv anything. impos anyth first place that, apologise.',
 'room.',
 'ey girl. r u? hope u r well del r bak! long time c! give call sum time lucyxx',
 '..k:)how much cost?',
 "'m home.",
 'ear, call tmorrow.pl accomodate.',
 'irst answer question.',
 'unshin quiz wkli q! win top soni dvd player u know countri algarv in? txt ansr 82277. £1.50 sp:tyron',
 "ant 2 get laid tonight? want real dog locat sent direct 2 ur mob? join uk' largest dog network bt txting gravel 69888! nt. ec2a. 31p.msg@150p",
 'haf msn. yijue@hotmail.com',
 'e there. call meet',
 'no. check room befor activ',
 "ou'll rcv msg chat svc. free hardcor servic text go to: 69988 u get noth u must age verifi yr network & tri",
 'ot c... lazi type... forgot ü lect... saw pouch like v nice...',
 ', text way',
 'ir, wait mail.',
 'swt thought: "nver get tire littl thing 4 lovabl persons.." coz..somtim littl thing occupi biggest part hearts.. gud ni8',
 'know are. pl open back?',
 'es see ya dot',
 'hat staff name take class us?',
 'reemsg repli text? randy, sexy, femal live local. luv hear u. netcollex ltd 08700621170150p per msg repli stop end',
 'mmma.wil call check in.our life begin qatar pl pray hard.',
 '..i delet contact why?',
 'indu got job birla soft ..',
 'wine flow nevering..',
 'thk cine better co need 2 go 2 plaza mah.',
 'k... ur typic reply...',
 "per request 'mell mell (oru minnaminungint nurungu vettam)' set callertun callers. press *9 copi friend callertun",
 'ou everywher dirt, floor, windows, even shirt. sometim open mouth, come flow out. dream world without you, half chore too. time joy me, lot tv show i.ll see. guess like thing must exist, like rain, hail mist, time done, becom one.',
 'aooooright work?',
 "'m leav hous now...",
 'ello, love. doing? get interview today? happy? good boy? think me?ar miss ?',
 'ustom servic annoncement. new year deliveri wait you. pleas call 07046744435 arrang deliveri',
 'ou winner u special select 2 receiv £1000 cash 4* holiday (flight inc) speak live oper 2 claim 0871277810810',
 "eep safe need miss alreadi envi everyon see' real life",
 'ew car hous parents.:)i new job hand:)',
 "'m love you. excit day spend you. make happy.",
 '-pl stop bootydeli (32/f) invit friend. repli yes-434 no-434 see her: www.sms.ac/u/bootydeli stop? send stop frnd 62468',
 'angbab ur order way. u receiv servic msg 2 download ur content. u not, goto wap. bangb. tv ur mobil internet/servic menu',
 'place ur point e cultur modul already.',
 'rgent! tri contact you. last weekend draw show £900 prize guaranteed. call 09061701939. claim code s89. valid 12hr',
 "frnd, best way avoid missunderstd wit belov one's?",
 'reat escape. fanci bridg need lager. see tomo',
 'es :)it complet form:)clark also utter waste.',
 'ir, need axi bank account bank address.',
 'mmm.. thk sure got time hop ard... ya, go 4 free abt... muz call u discuss liao...',
 'hat time come later?',
 'loodi hell, cant believ forgot surnam mr . ill give u clue, spanish begin m...',
 'ell, gonna finish bath now. good...fin night.',
 'et know got money carlo make call',
 'still go mall?',
 'urn friend stay whole show back til ~ &lt;#&gt; , feel free go ahead smoke $ &lt;#&gt; worth',
 'ext her. doesnt repli let know log',
 'i! spoke maneesha v. like know satisfi experience. repli toll free ye no.',
 'ou lift hope offer money. need. especi end month approach hurt studying. anyway gr8 weekend',
 'ol no. u trust me.',
 'k. gentleman treat digniti respect.',
 'e will, guy close?',
 'o noth great.by',
 "ello handsom ! find job ? lazi ? work toward get back net mummi ? where' boytoy ? miss ?",
 'aha awesome, minut',
 'leas call custom servic repres freephon 0808 145 4742 9am-11pm guarante £1000 cash £5000 prize!',
 'ave got xma radio times. get',
 'ju reach home. go bath first. si use net tell u finish k...',
 'uniqu enough? find 30th august. www.areyouunique.co.uk',
 "'m sorry. join leagu peopl dont keep touch. mean great deal me. friend time even great person cost. great week.|",
 ':)final complet course:)',
 'stop itself. howev suggest stay someon abl give or everi stool.',
 'ow doing? hope settl new school year. wishin gr8 day',
 'ud mrng dear hav nice day',
 'id u got person stori',
 'hamster dead? hey tmr meet 1pm orchard mrt?',
 'kate evening? hope see tomorrow bit bloodi babyjontet! txt back u can. :) xxx',
 'ound it, enc &lt;#&gt; , at?',
 'sent &lt;#&gt; buck',
 'ello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr &lt;decimal&gt; . keralacircl prepaid account balanc rs &lt;decimal&gt; . transact id kr &lt;#&gt; .',
 'oodmorn sleep ga.',
 'call alter 11 ok.',
 'ü say like dat dun buy ericsson oso cannot oredi lar...',
 "enter cabin pa said, '' happi b'day boss !!''. felt special. askd 4 lunch. lunch invit apartment. went there.",
 'ight yo, dat straight dogg',
 'ou pleas give us connect today &lt;decimal&gt; refund bill',
 'oth :) shoot big load get ready!',
 "hat' bruv, hope great break. reward semester.",
 'ome alway chat',
 ':)k:)good:)studi well.',
 'up... ü noe leh...',
 'ound great! home now?',
 'inal match head toward draw prediction.',
 'ired. slept well past nights.',
 'asi ah?sen got select mean good..',
 'take exam march 3',
 "eah should. think use gt atm register. sure there' anyway help let know. sure ready.",
 'k prob. take ur time.',
 'os call ubandu run without instal hard disk...you use os copi import file system give repair shop..',
 'orry, call later',
 'say leh... cours noth happen lar. say v romant ju bit lor. thk e nite sceneri nice leh.',
 '500 new mobil 2004, must go! txt: nokia no: 89545 & collect today!from £1 www.4-tc.biz 2optout 087187262701.50gbp/mtmsg18',
 'ould realli appreci call me. need someon talk to.',
 'ill u meet ur dream partner soon? ur career 2 flyng start? 2 find free, txt horo follow ur star sign, e. g. horo ari',
 'ey compani elama po mudyadhu.',
 'ife strict teacher... bcoz teacher teach lesson &amp; conduct exam, life first conduct exam &amp; teach lessons. happi morning. . .',
 'ear good morn',
 'et gandhipuram walk cross cut road. right side &lt;#&gt; street road turn first right.',
 'ear go rubber place',
 'orri batteri died, yeah',
 'es:)her tv alway avail work place..',
 'ext & meet someon sexi today. u find date even flirt u. join 4 10p. repli name & age eg sam 25. 18 -msg recd@thirtyeight penc',
 'print oh. &lt;#&gt; come upstair',
 'r ill littl closer like bu stop street',
 'you?when wil reach here?',
 'ew theory: argument win situation, lose person. dont argu ur friend just.. . . . kick &amp; say, alway correct.!',
 '447801259231 secret admir look 2 make contact u-find r*reveal think ur special-cal 09058094597',
 'omarrow final hear laptop case cant.',
 'leassssssseeeee tel v avent done sportsx',
 'kay. no, shine on. meant signing, sound better.',
 "lthough told u dat baig face watch realli like e watch u gave co fr u. thanx 4 everyth dat u'v done today, touched...",
 'rememb old commercial?',
 'oo late. said website. dont slipper',
 'ask call ok',
 'alli wont bat 2nd innings.',
 'didnt work oh. ok goodnight then. i.ll fix readi time wake up. dearli miss good night sleep.',
 'ongratul ur award 500 cd voucher 125gift guarante & free entri 2 100 wkli draw txt music 87066 tnc www.ldew.com1win150ppmx3age16',
 'anjith cal drpd deeraj deepak 5min hold',
 'en ur lovabl bcum angri wid u, dnt take seriously.. coz angri childish n true way show deep affection, care n luv!.. kettoda manda... nice day da.',
 'hat doing?how you?',
 'ps 3day also, ship compani take 2wks. way usp take week get lag may bribe nipost get stuff.',
 "'m back, lemm know readi",
 "on't necessarili expect done get back though headin",
 'mm yummi babe ... nice jolt suzi',
 'lover ? need ...',
 'e tri contact repli offer video handset? 750 anytim network mins? unlimit text? camcorder? repli call 08000930705',
 '‘m park next mini!!!! come today think?',
 '',
 'nyway go shop now. co si done yet. dun disturb u liao.',
 'no. luton 0125698789 ring ur around! h*',
 'ey realli horni want chat see nake text hot 69698 text charg 150pm unsubscrib text stop 69698',
 'hy dint come us.',
 'ame. wana plan trip sometm',
 'ot sure yet, still tri get hold',
 'r rington servic changed! 25 free credits! go club4mobiles.com choos content now! stop? txt club stop 87070. 150p/wk club4 po box1146 mk45 2wt',
 'evo. download flash. jealous?',
 'ington club: get uk singl chart mobil week choos top qualiti ringtone! messag free charge.',
 'ome mu, sort narcot situat',
 'ight end anoth day, morn come special way. may smile like sunni ray leav worri blue blue bay.',
 'mv bonu special 500 pound genuin hmv voucher won. answer 4 easi questions. play now! send hmv 86688 info:www.100percent-real.com',
 'sf guess, might well take 1 car',
 'objection. bf coming.',
 'hanx...',
 'ell rob mack gf theater',
 'wesome, see bit',
 'ust sent it. type food like?',
 'done? hand in? celebr full swing yet?',
 'ou got call tool?',
 '"wen u miss someone, person definit special u..... person special, miss them, keep-in-touch" gdeve..',
 'k. ask money far',
 'kie...',
 "eah think usual guy' still pass last night, get ahold anybodi let know throw",
 ', might come tonight class let earli',
 'k..',
 'babi im cruisin girl friend r u 2? give call hour home that alright fone fone love jenni xxx',
 'life mean lot me, love life, love peopl life, world call friends, call world:-).. ge:-)..',
 'ear,shal mail tonite.busi street,shal updat tonite.th look ok.varunnathu edukkukaye raksha ollu.but good one real sense.',
 'ey told name gautham ah?',
 'af u found him? feel stupid da v cam working.',
 'ops. 4 got bit.',
 'much buzi',
 'accident delet message. resend please.',
 "-mobil custom may claim free camera phone upgrad & pay & go sim card loyalty. call 0845 021 3680.offer end 28thfeb.t&c' appli",
 'nless situat go gurl would appropri',
 'urt me... teas me... make cry... end life die plz keep one rose grave say stupid miss u.. nice day bslvyl',
 'cant pick phone right now. pl send messag',
 "eed coffe run tomo?can't believ time week alreadi",
 'wesome, rememb last time got somebodi high first time diesel :v',
 'hit realli shock scary, cant imagin second. def night out. u think somewher could crash night, save taxi?',
 'h way food fridge! want go meal tonight?',
 'e womdarful actor',
 'ms. ac blind date 4u!: rodds1 21/m aberdeen, unit kingdom. check http://img. sms. ac/w/icmb3cktz8r7!-4 blind date send hide',
 'up... remb... think book...',
 'os ask u wana meet up?',
 'ol yes. friendship hang thread caus u buy stuff.',
 'hemob> check newest select content, games, tones, gossip, babe sport, keep mobil fit funki text wap 82468',
 'garag keys? bookshelf',
 'oday accept day..u accept as? brother sister lover dear1 best1 clos1 lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'hink ur smart ? win £200 week weekli quiz, text play 85222 now!t&c winnersclub po box 84, m26 3uz. 16+. gbp1.50/week',
 "e say give call friend' got money definit buy end week",
 'way u 2day, normal way&thi real me. ur unique&i hope know u 4 rest mylife. hope u find wot lost.',
 'ou made day. great day too.',
 '.k:)advanc happi pongal.',
 'mmm... guess go 4 kb n power yoga... haha, dunno tahan power yoga anot... thk got lo oso, forgot liao...',
 'ot realli dude, friend afraid :(',
 'ecemb only! mobil 11mths+? entitl updat latest colour camera mobil free! call mobil updat co free 08002986906',
 'offe cake, guess...',
 'erri christma babe, love ya *kisses*',
 'ey... dont go watch x men lunch... haha',
 'ud u tell ppl im gona b bit l8 co 2 buse hav gon past co full & im still waitin 4 1. pete x',

### Create Bag of Words

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
cv = CountVectorizer(max_features=2500, ngram_range=(1, 2))

In [10]:
# independant features
x = cv.fit_transform(corpus).toarray()

In [11]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5574, 2500))

In [12]:
cv.vocabulary_

{'point': np.int64(1704),
 'avail': np.int64(271),
 'great': np.int64(942),
 'world': np.int64(2445),
 'la': np.int64(1168),
 'cine': np.int64(482),
 'got': np.int64(933),
 'wat': np.int64(2359),
 'lar': np.int64(1179),
 'joke': np.int64(1137),
 'wif': np.int64(2409),
 'ree': np.int64(1791),
 'entri': np.int64(735),
 'wkli': np.int64(2432),
 'comp': np.int64(527),
 'win': np.int64(2414),
 'cup': np.int64(581),
 'final': np.int64(807),
 'may': np.int64(1325),
 'text': np.int64(2116),
 'receiv': np.int64(1783),
 'question': np.int64(1750),
 'std': np.int64(2037),
 'txt': np.int64(2227),
 'rate': np.int64(1763),
 'appli': np.int64(232),
 'ree entri': np.int64(1793),
 'std txt': np.int64(2038),
 'txt rate': np.int64(2231),
 'rate appli': np.int64(1764),
 'dun': np.int64(686),
 'say': np.int64(1880),
 'earli': np.int64(695),
 'alreadi': np.int64(203),
 'ah': np.int64(184),
 'think': np.int64(2135),
 'goe': np.int64(914),
 'usf': np.int64(2300),
 'live': np.int64(1244),
 'around': np.int64(245),
 'though': np.int64(2145),
 'reemsg': np.int64(1795),
 'hey': np.int64(1019),
 'darl': np.int64(597),
 'week': np.int64(2376),
 'word': np.int64(2439),
 'back': np.int64(295),
 'like': np.int64(1231),
 'fun': np.int64(867),
 'still': np.int64(2039),
 'ok': np.int64(1543),
 'xxx': np.int64(2467),
 'send': np.int64(1909),
 '50': np.int64(102),
 'brother': np.int64(369),
 'speak': np.int64(2012),
 'me': np.int64(1327),
 'treat': np.int64(2204),
 'per': np.int64(1651),
 'request': np.int64(1818),
 'mell': np.int64(1341),
 'set': np.int64(1921),
 'callertun': np.int64(415),
 'callers': np.int64(413),
 'press': np.int64(1726),
 'copi': np.int64(553),
 'friend': np.int64(852),
 'per request': np.int64(1655),
 'callertun callers': np.int64(416),
 'callers press': np.int64(414),
 'press copi': np.int64(1727),
 'copi friend': np.int64(554),
 'friend callertun': np.int64(853),
 'valu': np.int64(2310),
 'network': np.int64(1460),
 'custom': np.int64(585),
 'select': np.int64(1903),
 '900': np.int64(145),
 'prize': np.int64(1733),
 'reward': np.int64(1829),
 'claim': np.int64(484),
 'call': np.int64(393),
 'code': np.int64(502),
 'valid': np.int64(2308),
 '12': np.int64(38),
 'hour': np.int64(1049),
 'only': np.int64(1563),
 '900 prize': np.int64(146),
 'claim call': np.int64(486),
 'claim code': np.int64(487),
 'ad': np.int64(165),
 'mobil': np.int64(1387),
 '11': np.int64(36),
 'month': np.int64(1407),
 'more': np.int64(1412),
 'entitl': np.int64(733),
 'updat': np.int64(2265),
 'latest': np.int64(1189),
 'colour': np.int64(513),
 'camera': np.int64(424),
 'free': np.int64(839),
 'co': np.int64(499),
 'ad mobil': np.int64(166),
 'entitl updat': np.int64(734),
 'updat latest': np.int64(2267),
 'latest colour': np.int64(1191),
 'free call': np.int64(843),
 'call mobil': np.int64(405),
 'mobil updat': np.int64(1395),
 'updat co': np.int64(2266),
 'co free': np.int64(500),
 'gonna': np.int64(920),
 'home': np.int64(1039),
 'soon': np.int64(2004),
 'want': np.int64(2349),
 'talk': np.int64(2097),
 'stuff': np.int64(2059),
 'tonight': np.int64(2187),
 'enough': np.int64(729),
 'today': np.int64(2169),
 'want talk': np.int64(2355),
 'chanc': np.int64(459),
 'cash': np.int64(443),
 '100': np.int64(27),
 '20': np.int64(57),
 '000': np.int64(2),
 'pound': np.int64(1717),
 'cost': np.int64(556),
 '150p': np.int64(44),
 'day': np.int64(603),
 '16': np.int64(49),
 'repli': np.int64(1810),
 'hl': np.int64(1029),
 'info': np.int64(1096),
 'chanc win': np.int64(460),
 'cost 150p': np.int64(558),
 'repli hl': np.int64(1812),
 'rgent': np.int64(1830),
 'no': np.int64(1483),
 'www': np.int64(2458),
 'net': np.int64(1458),
 'pobox': np.int64(1698),
 'week free': np.int64(2378),
 'txt word': np.int64(2233),
 've': np.int64(2312),
 'search': np.int64(1888),
 'right': np.int64(1836),
 'thank': np.int64(2124),
 'promis': np.int64(1743),
 'wont': np.int64(2438),
 'take': np.int64(2094),
 'help': np.int64(1013),
 'wonder': np.int64(2437),
 'bless': np.int64(339),
 'times': np.int64(2160),
 'date': np.int64(601),
 'sunday': np.int64(2074),
 'will': np.int64(2413),
 'use': np.int64(2298),
 'credit': np.int64(574),
 'click': np.int64(494),
 'wap': np.int64(2356),
 'link': np.int64(1240),
 'next': np.int64(1472),
 'messag': np.int64(1347),
 'here': np.int64(1018),
 'http': np.int64(1055),
 'com': np.int64(516),
 'watch': np.int64(2363),
 'rememb': np.int64(1804),
 'name': np.int64(1446),
 'ye': np.int64(2474),
 'did': np.int64(634),
 'naughti': np.int64(1451),
 'make': np.int64(1301),
 'ine': np.int64(1095),
 'that': np.int64(2127),
 'way': np.int64(2366),
 'feel': np.int64(796),
 'dont': np.int64(664),
 'miss': np.int64(1372),
 'team': np.int64(2103),
 'news': np.int64(1471),
 'ur': np.int64(2268),
 'nation': np.int64(1447),
 '87077': np.int64(143),
 'eg': np.int64(708),
 'england': np.int64(726),
 'try': np.int64(2215),
 'dont miss': np.int64(666),
 'serious': np.int64(1917),
 'go': np.int64(903),
 'tri': np.int64(2205),
 'ha': np.int64(969),
 'pay': np.int64(1645),
 'first': np.int64(815),
 'da': np.int64(591),
 'stock': np.int64(2041),
 'comin': np.int64(524),
 'finish': np.int64(814),
 'lunch': np.int64(1290),
 'lor': np.int64(1263),
 'ard': np.int64(238),
 'smth': np.int64(1982),
 'already': np.int64(204),
 'alright': np.int64(205),
 'meet': np.int64(1336),
 'ust': np.int64(2301),
 'eat': np.int64(702),
 'realli': np.int64(1778),
 'hungri': np.int64(1060),
 'tho': np.int64(2144),
 'sucks': np.int64(2067),
 'mark': np.int64(1313),
 'get': np.int64(881),
 'know': np.int64(1164),
 'sick': np.int64(1942),
 'turn': np.int64(2223),
 'pizza': np.int64(1674),
 'lol': np.int64(1256),
 'ol': np.int64(1548),
 'alway': np.int64(207),
 'id': np.int64(1071),
 'catch': np.int64(450),
 'bu': np.int64(373),
 'fri': np.int64(850),
 'egg': np.int64(709),
 'tea': np.int64(2101),
 'mom': np.int64(1402),
 'left': np.int64(1211),
 'dinner': np.int64(646),
 'love': np.int64(1269),
 'amp': np.int64(212),
 'pack': np.int64(1628),
 'car': np.int64(438),
 'now': np.int64(1508),
 'let': np.int64(1219),
 'there': np.int64(2131),
 'room': np.int64(1851),
 'let know': np.int64(1220),
 'work': np.int64(2441),
 'feel like': np.int64(798),
 'ait': np.int64(193),
 'clear': np.int64(493),
 'sure': np.int64(2080),
 'us': np.int64(2296),
 'eah': np.int64(691),
 'till': np.int64(2153),
 'you': np.int64(2490),
 'tell': np.int64(2108),
 'anyth': np.int64(224),
 'quick': np.int64(1752),
 'hank': np.int64(981),
 'rington': np.int64(1839),
 'uk': np.int64(2243),
 'charg': np.int64(464),
 'pleas': np.int64(1685),
 'confirm': np.int64(538),
 'mobil charg': np.int64(1391),
 'up': np.int64(2264),
 'look': np.int64(1260),
 'time': np.int64(2154),
 'msg': np.int64(1429),
 'again': np.int64(180),
 'learn': np.int64(1203),
 '2nd': np.int64(78),
 'lesson': np.int64(1217),
 'go home': np.int64(907),
 'done': np.int64(663),
 'see': np.int64(1896),
 'letter': np.int64(1221),
 'nyth': np.int64(1530),
 'ello': np.int64(715),
 'how': np.int64(1052),
 'saturday': np.int64(1875),
 'decid': np.int64(615),
 'tomo': np.int64(2177),
 'invit': np.int64(1103),
 'anything': np.int64(225),
 'ls': np.int64(1279),
 'ahead': np.int64(186),
 'weekend': np.int64(2382),
 'abiola': np.int64(149),
 'great weekend': np.int64(944),
 'forget': np.int64(831),
 'need': np.int64(1455),
 'crave': np.int64(571),
 'sweet': np.int64(2085),
 'need you': np.int64(1457),
 'burn': np.int64(377),
 'sm': np.int64(1974),
 'nokia': np.int64(1489),
 'camcorder': np.int64(421),
 '08000930705': np.int64(13),
 'deliveri': np.int64(624),
 'tomorrow': np.int64(2178),
 'mobil free': np.int64(1393),
 'pleas call': np.int64(1686),
 'call 08000930705': np.int64(394),
 'deliveri tomorrow': np.int64(625),
 'ho': np.int64(1031),
 'reat': np.int64(1781),
 'hope': np.int64(1042),
 'man': np.int64(1306),
 'well': np.int64(2390),
 'lt': np.int64(1281),
 'gt': np.int64(949),
 'lt gt': np.int64(1283),
 'calls': np.int64(418),
 'messages': np.int64(1351),
 'miss call': np.int64(1374),
 'nigeria': np.int64(1477),
 'air': np.int64(191),
 'on': np.int64(1553),
 'tyler': np.int64(2237),
 'can': np.int64(428),
 'could': np.int64(563),
 'mayb': np.int64(1326),
 'ask': np.int64(253),
 'bit': np.int64(335),
 'am': np.int64(208),
 'even': np.int64(748),
 'kept': np.int64(1150),
 'weak': np.int64(2369),
 'hospit': np.int64(1045),
 'want go': np.int64(2351),
 'hat': np.int64(993),
 'saw': np.int64(1879),
 'class': np.int64(491),
 'think me': np.int64(2137),
 'first time': np.int64(816),
 'usual': np.int64(2304),
 'run': np.int64(1861),
 'half': np.int64(973),
 'almost': np.int64(201),
 'whole': np.int64(2406),
 'second': np.int64(1891),
 'like lt': np.int64(1234),
 'ride': np.int64(1835),
 'morn': np.int64(1413),
 'place': np.int64(1679),
 'ow': np.int64(1618),
 'never': np.int64(1464),
 'realiz': np.int64(1777),
 'thought': np.int64(2146),
 'it': np.int64(1119),
 'sinc': np.int64(1952),
 'best': np.int64(324),
 'seem': np.int64(1901),
 'happi': np.int64(986),
 'the': np.int64(2128),
 'sorri': np.int64(2005),
 'give': np.int64(898),
 'ms': np.int64(1428),
 'ac': np.int64(153),
 'new': np.int64(1465),
 'red': np.int64(1788),
 'play': np.int64(1682),
 'ice': np.int64(1070),
 'correct': np.int64(555),
 'end': np.int64(723),
 'yesterday': np.int64(2483),
 'find': np.int64(809),
 'ongrats': np.int64(1558),
 'year': np.int64(2477),
 'special': np.int64(2015),
 'cinema': np.int64(483),
 'pass': np.int64(1641),
 'yours': np.int64(2494),
 'etc': np.int64(744),
 'bx420': np.int64(383),
 'ip4': np.int64(1107),
 '5we': np.int64(118),
 '150pm': np.int64(47),
 'out': np.int64(1614),
 'yours call': np.int64(2495),
 'etc free': np.int64(745),
 'bx420 ip4': np.int64(384),
 'ip4 5we': np.int64(1108),
 '5we 150pm': np.int64(119),
 'miss out': np.int64(1376),
 'orry': np.int64(1593),
 'later': np.int64(1186),
 'meeting': np.int64(1339),
 'orry call': np.int64(1594),
 'call later': np.int64(403),
 'ell': np.int64(713),
 'reach': np.int64(1770),
 'es': np.int64(740),
 'pick': np.int64(1666),
 'move': np.int64(1420),
 'pain': np.int64(1631),
 'kill': np.int64(1157),
 'way home': np.int64(2367),
 'good': np.int64(922),
 'girl': np.int64(896),
 'situat': np.int64(1961),
 'ts': np.int64(2216),
 'part': np.int64(1637),
 'check': np.int64(473),
 'orri': np.int64(1591),
 'roommat': np.int64(1852),
 'took': np.int64(2190),
 'forever': np.int64(830),
 'come': np.int64(517),
 'doubl': np.int64(669),
 'hair': np.int64(972),
 'said': np.int64(1866),
 'wun': np.int64(2457),
 'cut': np.int64(588),
 'short': np.int64(1936),
 'nice': np.int64(1475),
 'customer': np.int64(587),
 'follow': np.int64(824),
 'recent': np.int64(1786),
 'review': np.int64(1828),
 'mob': np.int64(1385),
 'award': np.int64(281),
 'bonu': np.int64(344),
 'no award': np.int64(1484),
 'prize call': np.int64(1735),
 'oday': np.int64(1533),
 'song': np.int64(2000),
 'frnd': np.int64(859),
 'rpli': np.int64(1857),
 'me send': np.int64(1330),
 'complimentari': np.int64(532),
 'trip': np.int64(2210),
 '1000': np.int64(30),
 'di': np.int64(633),
 '18': np.int64(50),
 '10': np.int64(24),
 'ur award': np.int64(2270),
 'hear': np.int64(1004),
 'plane': np.int64(1681),
 'lucki': np.int64(1288),
 'save': np.int64(1878),
 'money': np.int64(1406),
 'hee': np.int64(1009),
 'babe': np.int64(291),
 'im': np.int64(1081),
 'wanna': np.int64(2348),
 'something': np.int64(1997),
 'xx': np.int64(2466),
 'where': np.int64(2402),
 'call now': np.int64(407),
 'wait': np.int64(2337),
 'call free': np.int64(401),
 'cool': np.int64(552),
 'respect': np.int64(1819),
 'hat cool': np.int64(994),
 'peopl': np.int64(1649),
 'much': np.int64(1435),
 'pa': np.int64(1626),
 'oe': np.int64(1534),
 'oper': np.int64(1577),
 'job': np.int64(1133),
 'ta': np.int64(2091),
 'hi': np.int64(1022),
 'hi hi': np.int64(1023),
 'ou': np.int64(1603),
 'stop': np.int64(2044),
 'urgnt': np.int64(2293),
 'real': np.int64(1776),
 'yo': np.int64(2487),
 'ticket': np.int64(2151),
 'one': np.int64(1554),
 'start': np.int64(2032),
 'came': np.int64(422),
 'bed': np.int64(314),
 'too': np.int64(2189),
 'gotta': np.int64(939),
 'kano': np.int64(1144),
 'il': np.int64(1079),
 'download': np.int64(672),
 'wen': np.int64(2391),
 'do': np.int64(654),
 'don': np.int64(661),
 'stand': np.int64(2028),
 'close': np.int64(496),
 'll': np.int64(1246),
 'anoth': np.int64(218),
 'night': np.int64(1478),
 'spent': np.int64(2021),
 'late': np.int64(1185),
 'afternoon': np.int64(177),
 'mean': np.int64(1332),
 'includ': np.int64(1091),
 'sorry': np.int64(2006),
 'pleasur': np.int64(1688),
 'smile': np.int64(1976),
 'troubl': np.int64(2211),
 'rain': np.int64(1757),
 'hurt': np.int64(1063),
 'someon': np.int64(1992),
 'smiling': np.int64(1977),
 'leas': np.int64(1204),
 'servic': np.int64(1918),
 'repres': np.int64(1817),
 '0800': np.int64(10),
 '10am': np.int64(32),
 'guarante': np.int64(956),
 '5000': np.int64(110),
 'leas call': np.int64(1205),
 'call custom': np.int64(400),
 'custom servic': np.int64(586),
 'servic repres': np.int64(1919),
 'guarante 1000': np.int64(957),
 '1000 cash': np.int64(31),
 'cash 5000': np.int64(445),
 '5000 prize': np.int64(113),
 'avent': np.int64(275),
 'plan': np.int64(1680),
 'buy': np.int64(381),
 '530': np.int64(115),
 'show': np.int64(1937),
 'simpli': np.int64(1951),
 'password': np.int64(1643),
 'po': np.int64(1696),
 'box': np.int64(357),
 'po box': np.int64(1697),
 'atch': np.int64(261),
 'movie': np.int64(1422),
 'abt': np.int64(152),
 'wat abt': np.int64(2360),
 'load': np.int64(1248),
 'loan': np.int64(1249),
 'wk': np.int64(2430),
 'forgot': np.int64(832),
 'shower': np.int64(1939),
 'caus': np.int64(451),
 'prob': np.int64(1738),
 'need get': np.int64(1456),
 'get home': np.int64(884),
 'coffe': np.int64(503),
 'anymore': np.int64(222),
 'noth': np.int64(1505),
 'els': np.int64(716),
 'kay': np.int64(1146),
 'price': np.int64(1729),
 'long': np.int64(1258),
 'ave': np.int64(272),
 'pick up': np.int64(1668),
 'gone': np.int64(919),
 'drive': np.int64(681),
 'test': np.int64(2115),
 'yet': np.int64(2484),
 'guess': np.int64(965),
 'gave': np.int64(876),
 'boston': np.int64(352),
 'men': np.int64(1344),
 'chang': np.int64(462),
 'locat': np.int64(1251),
 'someth': np.int64(1994),
 'cuz': np.int64(590),
 'page': np.int64(1629),
 'life': np.int64(1226),
 'umma': np.int64(2246),
 'lot': np.int64(1266),
 'dear': np.int64(614),
 'wish': np.int64(2421),
 'birthday': np.int64(333),
 'ight': np.int64(1077),
 'hit': np.int64(1028),
 'would': np.int64(2452),
 'address': np.int64(169),
 'consid': np.int64(541),
 'comput': np.int64(533),
 'old': np.int64(1549),
 'people': np.int64(1650),
 'better': np.int64(326),
 'ont': np.int64(1564),
 'worry': np.int64(2447),
 'things': np.int64(2134),
 'mah': np.int64(1297),
 'ent': np.int64(730),
 'contact': np.int64(542),
 'last': np.int64(1180),
 'draw': np.int64(673),
 'guaranteed': np.int64(958),
 '12hr': np.int64(39),
 '150ppm': np.int64(48),
 'tri contact': np.int64(2206),
 'contact you': np.int64(546),
 'last weekend': np.int64(1184),
 'weekend draw': np.int64(2383),
 'draw show': np.int64(675),
 'prize guaranteed': np.int64(1737),
 'guaranteed call': np.int64(959),
 'valid 12hr': np.int64(2309),
 'anyway': np.int64(228),
 'fine': np.int64(812),
 'juz': np.int64(1142),
 'tt': np.int64(2219),
 'eatin': np.int64(703),
 'weight': np.int64(2387),
 'haha': np.int64(971),
 'happened': np.int64(985),
 'enter': np.int64(731),
 'cabin': np.int64(387),
 'boss': np.int64(350),
 'felt': np.int64(799),
 'askd': np.int64(254),
 'went': np.int64(2392),
 'enter cabin': np.int64(732),
 'cabin pa': np.int64(388),
 'pa said': np.int64(1627),
 'said happi': np.int64(1867),
 'happi day': np.int64(988),
 'day boss': np.int64(604),
 'boss felt': np.int64(351),
 'felt special': np.int64(800),
 'special askd': np.int64(2016),
 'askd lunch': np.int64(255),
 'lunch lunch': np.int64(1292),
 'lunch invit': np.int64(1291),
 'invit apartment': np.int64(1104),
 'went there': np.int64(2393),
 'winner': np.int64(2419),
 'holiday': np.int64(1035),
 'flight': np.int64(821),
 'inc': np.int64(1089),
 'min': np.int64(1358),
 'ou winner': np.int64(1608),
 'winner special': np.int64(2420),
 'special select': np.int64(2018),
 'select receiv': np.int64(1904),
 'receiv 1000': np.int64(1784),
 'speak live': np.int64(2013),
 'live oper': np.int64(1245),
 'oper claim': np.int64(1578),
 'must': np.int64(1442),
 'friday': np.int64(851),
 'mm': np.int64(1381),
 'mi': np.int64(1354),
 'uncl': np.int64(2250),
 'inform': np.int64(1097),
 'school': np.int64(1884),
 'pl': np.int64(1675),
 'food': np.int64(826),
 'rivate': np.int64(1844),
 '2004': np.int64(63),
 'account': np.int64(157),
 'statement': np.int64(2033),
 'points': np.int64(1705),
 'identifi': np.int64(1073),
 'expir': np.int64(770),
 'account statement': np.int64(158),
 'identifi code': np.int64(1074),
 '2000': np.int64(59),
 'caller': np.int64(411),
 '03': np.int64(6),
 'landlin': np.int64(1174),
 'rgent mobil': np.int64(1832),
 'award 2000': np.int64(282),
 'bonu caller': np.int64(345),
 'caller prize': np.int64(412),
 'call landlin': np.int64(402),
 'ere': np.int64(738),
 'al': np.int64(195),
 'voda': np.int64(2325),
 'number': np.int64(1524),
 '350': np.int64(87),
 'match': np.int64(1315),
 '08712300220': np.int64(18),
 'quot': np.int64(1755),
 'standard': np.int64(2029),
 'app': np.int64(229),
 'voda number': np.int64(2326),
 'number end': np.int64(1526),
 'receiv 350': np.int64(1785),
 '350 award': np.int64(88),
 'match pleas': np.int64(1316),
 'call 08712300220': np.int64(396),
 '08712300220 quot': np.int64(19),
 'quot claim': np.int64(1756),
 'standard rate': np.int64(2030),
 'mu': np.int64(1434),
 'wat time': np.int64(2361),
 'ood': np.int64(1567),
 'sent': np.int64(1915),
 'bother': np.int64(353),
 'over': np.int64(1617),
 'ey': np.int64(773),
 'del': np.int64(620),
 'bak': np.int64(298),
 'give call': np.int64(899),
 'ear': np.int64(693),
 'answer': np.int64(220),
 'unshin': np.int64(2258),
 'quiz': np.int64(1754),
 'top': np.int64(2191),
 'soni': np.int64(2001),
 'dvd': np.int64(690),
 'player': np.int64(1684),
 'in': np.int64(1087),
 '82277': np.int64(133),
 'sp': np.int64(2010),
 'unshin quiz': np.int64(2259),
 'soni dvd': np.int64(2002),
 'ant': np.int64(221),
 'laid': np.int64(1171),
 'dog': np.int64(658),
 'direct': np.int64(648),
 'join': np.int64(1135),
 'bt': np.int64(371),
 'txting': np.int64(2235),
 'nt': np.int64(1519),
 'ec2a': np.int64(706),
 'ur mob': np.int64(2282),
 'join uk': np.int64(1136),
 'haf': np.int64(970),
 'yijue': np.int64(2485),
 'activ': np.int64(163),
 'chat': np.int64(469),
 'to': np.int64(2166),
 'age': np.int64(181),
 'yr': np.int64(2497),
 'ot': np.int64(1597),
 'lazi': np.int64(1199),
 'type': np.int64(2238),
 'lect': np.int64(1210),
 'ir': np.int64(1111),
 'mail': np.int64(1299),
 'ir wait': np.int64(1112),
 'swt': np.int64(2089),
 'tire': np.int64(2161),
 'littl': np.int64(1243),
 'thing': np.int64(2133),
 'lovabl': np.int64(1268),
 'coz': np.int64(568),
 'gud': np.int64(960),
 'ni8': np.int64(1474),
 'gud ni8': np.int64(963),
 'are': np.int64(239),
 'open': np.int64(1576),
 'ya': np.int64(2470),
 'local': np.int64(1250),
 'luv': np.int64(1293),
 'ltd': np.int64(1285),
 'per msg': np.int64(1654),
 'repli stop': np.int64(1813),
 'stop end': np.int64(2045),
 'wil': np.int64(2412),
 'our': np.int64(1613),
 'begin': np.int64(320),
 'qatar': np.int64(1748),
 'pray': np.int64(1723),
 'hard': np.int64(992),
 'delet': np.int64(622),
 'got job': np.int64(935),
 'wine': np.int64(2418),
 'thk': np.int64(2142),
 'reply': np.int64(1815),
 'shirt': np.int64(1932),
 'sometim': np.int64(1998),
 'dream': np.int64(677),
 'without': np.int64(2428),
 'joy': np.int64(1138),
 'tv': np.int64(2224),
 'becom': np.int64(313),
 'll see': np.int64(1247),
 'leav': np.int64(1207),
 'hous': np.int64(1050),
 'doing': np.int64(660),
 'happy': np.int64(991),
 'boy': np.int64(359),
 'ar': np.int64(236),
 'ustom': np.int64(2303),
 'arrang': np.int64(247),
 'new year': np.int64(1470),
 'wait you': np.int64(2339),

In [13]:
# output features
y = pd.get_dummies(messages['label'])

In [14]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5569  False   True
5570   True  False
5571   True  False
5572   True  False
5573   True  False

[5574 rows x 2 columns]

In [15]:
y = y.iloc[:,0].values

In [16]:
y

array([ True,  True, False, ...,  True,  True,  True], shape=(5574,))

In [17]:
# train test split
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [19]:
from sklearn.naive_bayes import MultinomialNB

In [20]:
spam_detect_model = MultinomialNB().fit(x_train, y_train)

In [21]:
spam_detect_model

MultinomialNB()

In [23]:
y_pred = spam_detect_model.predict(x_test)

In [24]:
from sklearn.metrics import accuracy_score, classification_report

In [25]:
accuracy_score(y_test, y_pred)

0.9811659192825112

In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.95      0.92      0.93       161
        True       0.99      0.99      0.99       954

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115