## XGBoost Classification

In [1]:
# import all the libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
df = pd.read_csv('Travel.csv')

In [3]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [4]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [5]:
#Age
df.Age.fillna(df.Age.median(), inplace=True)

#TypeofContract
df.TypeofContact.fillna(df.TypeofContact.mode()[0], inplace=True)

#DurationOfPitch
df.DurationOfPitch.fillna(df.DurationOfPitch.median(), inplace=True)

#NumberOfFollowups
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0], inplace=True)

#PreferredPropertyStar
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0], inplace=True)

#NumberOfTrips
df.NumberOfTrips.fillna(df.NumberOfTrips.median(), inplace=True)

#NumberOfChildrenVisiting
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0], inplace=True)

#MonthlyIncome
df.MonthlyIncome.fillna(df.MonthlyIncome.median(), inplace=True)

C:\Users\om_da\AppData\Local\Temp\ipykernel_16328\3927510868.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Age.fillna(df.Age.median(), inplace=True)
C:\Users\om_da\AppData\Local\Temp\ipykernel_16328\3927510868.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.TypeofContact.fillna(df.TypeofContact.mode()[0], inplace=True)
C:\Users\om_da\AppData\Local\Temp\ipykernel_16328\3927510868.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.DurationOfPitch.fillna(df.DurationOfPitch.median(), inplace=True)
C:\Users\om_da\AppData\Local\Temp\ipykernel_16328\3927510868.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0], inplace=True)
C:\Users\om_da\AppData\Local\Temp\ipykernel_16328\3927510868.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0], inplace=True)
C:\Users\om_da\AppData\Local\Temp\ipykernel_16328\3927510868.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NumberOfTrips.fillna(df.NumberOfTrips.median(), inplace=True)
C:\Users\om_da\AppData\Local\Temp\ipykernel_16328\3927510868.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0], inplace=True)
C:\Users\om_da\AppData\Local\Temp\ipykernel_16328\3927510868.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.MonthlyIncome.fillna(df.MonthlyIncome.median(), inplace=True)

In [6]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [7]:
print(df['Gender'].value_counts())
print(df['MaritalStatus'].value_counts())
print(df['TypeofContact'].value_counts())

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64
MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64
TypeofContact
Self Enquiry       3469
Company Invited    1419
Name: count, dtype: int64

In [8]:
df['Gender'] = df['Gender'].replace('Fe Male','Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single', 'Unmarried')

In [9]:
# drop unnecessary columns

df.drop(columns=['CustomerID'], axis=1, inplace=True)

In [10]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [11]:
# create a new feature for total number of visiting

df['TotalVisits'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfPersonVisiting', 'NumberOfChildrenVisiting'], axis=1, inplace=True)

In [12]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisits
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [13]:
# train test split

from sklearn.model_selection import train_test_split

In [14]:
# dependant and independant features

x = df.drop(columns=['ProdTaken'], axis=1)
y = df['ProdTaken']

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [16]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4888 non-null   float64
 1   TypeofContact           4888 non-null   object
 2   CityTier                4888 non-null   int64
 3   DurationOfPitch         4888 non-null   float64
 4   Occupation              4888 non-null   object
 5   Gender                  4888 non-null   object
 6   NumberOfFollowups       4888 non-null   float64
 7   ProductPitched          4888 non-null   object
 8   PreferredPropertyStar   4888 non-null   float64
 9   MaritalStatus           4888 non-null   object
 10  NumberOfTrips           4888 non-null   float64
 11  Passport                4888 non-null   int64
 12  PitchSatisfactionScore  4888 non-null   int64
 13  OwnCar                  4888 non-null   int64
 14  Designation             4888 non-null   object
 15  MonthlyIncome           4888 non-null   float64
 16  TotalVisits             4888 non-null   float64
dtypes: float64(7), int64(4), object(6)
memory usage: 649.3+ KB

In [17]:
# apply encoding to categorical features

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [18]:
cat_features = x.select_dtypes(include='object').columns
num_features = x.select_dtypes(exclude='object').columns

In [19]:
one_hot_encoder = OneHotEncoder(drop='first')
scaler = StandardScaler()

In [20]:
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', one_hot_encoder, cat_features),
        ('scaler', scaler, num_features)
    ]
)

In [21]:
x_train = preprocessor.fit_transform(x_train)

In [22]:
x_test = preprocessor.transform(x_test)

## XGboost Classifier Training

In [23]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.0.2-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in d:\ds, ml, dl, nlp\machine learning\venv\lib\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in d:\ds, ml, dl, nlp\machine learning\venv\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.0.2-py3-none-win_amd64.whl (150.0 MB)
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 1.8/150.0 MB 9.2 MB/s eta 0:00:17
    --------------------------------------- 3.7/150.0 MB 9.4 MB/s eta 0:00:16
   - -------------------------------------- 6.0/150.0 MB 9.4 MB/s eta 0:00:16
   -- ------------------------------------- 8.1/150.0 MB 9.5 MB/s eta 0:00:15
   -- ------------------------------------- 10.2/150.0 MB 9.5 MB/s eta 0:00:15
   --- ------------------------------------ 12.3/150.0 MB 9.6 MB/s eta 0:00:15
   --- ------------------------------------ 14.7/150.0 MB 9.7 MB/s eta 0:00:14
   ---- ----------------------------------- 17.0/150.0 MB 9.9 MB/s eta 0:00:14
   ----- ---------------------------------- 19.1/150.0 MB 9.9 MB/s eta 0:00:14
   ----- ---------------------------------- 21.5/150.0 MB 10.0 MB/s eta 0:00:13
   ------ --------------------------------- 23.6/150.0 MB 10.0 MB/s eta 0:00:13
   ------ --------------------------------- 25.7/150.0 MB 9.9 MB/s eta 0:00:13
   ------- -------------------------------- 27.5/150.0 MB 9.9 MB/s eta 0:00:13
   ------- -------------------------------- 29.9/150.0 MB 10.0 MB/s eta 0:00:13
   -------- ------------------------------- 32.2/150.0 MB 10.0 MB/s eta 0:00:12
   --------- ------------------------------ 34.6/150.0 MB 10.1 MB/s eta 0:00:12
   --------- ------------------------------ 37.0/150.0 MB 10.1 MB/s eta 0:00:12
   ---------- ----------------------------- 39.1/150.0 MB 10.1 MB/s eta 0:00:11
   ---------- ----------------------------- 41.2/150.0 MB 10.1 MB/s eta 0:00:11
   ----------- ---------------------------- 43.5/150.0 MB 10.1 MB/s eta 0:00:11
   ------------ --------------------------- 46.1/150.0 MB 10.1 MB/s eta 0:00:11
   ------------ --------------------------- 48.2/150.0 MB 10.1 MB/s eta 0:00:11
   ------------- -------------------------- 50.9/150.0 MB 10.1 MB/s eta 0:00:10
   -------------- ------------------------- 53.5/150.0 MB 10.1 MB/s eta 0:00:10
   -------------- ------------------------- 55.8/150.0 MB 10.1 MB/s eta 0:00:10
   --------------- ------------------------ 58.5/150.0 MB 10.1 MB/s eta 0:00:10
   ---------------- ----------------------- 60.0/150.0 MB 10.1 MB/s eta 0:00:09
   ---------------- ----------------------- 61.6/150.0 MB 10.0 MB/s eta 0:00:09
   ---------------- ----------------------- 63.2/150.0 MB 9.8 MB/s eta 0:00:09
   ----------------- ---------------------- 64.7/150.0 MB 9.7 MB/s eta 0:00:09
   ----------------- ---------------------- 66.1/150.0 MB 9.7 MB/s eta 0:00:09
   ----------------- ---------------------- 67.1/150.0 MB 9.5 MB/s eta 0:00:09
   ------------------ --------------------- 67.9/150.0 MB 9.3 MB/s eta 0:00:09
   ------------------ --------------------- 68.9/150.0 MB 9.2 MB/s eta 0:00:09
   ------------------ --------------------- 70.3/150.0 MB 9.1 MB/s eta 0:00:09
   ------------------- -------------------- 71.3/150.0 MB 9.0 MB/s eta 0:00:09
   ------------------- -------------------- 72.4/150.0 MB 8.9 MB/s eta 0:00:09
   ------------------- -------------------- 72.9/150.0 MB 8.7 MB/s eta 0:00:09
   ------------------- -------------------- 74.2/150.0 MB 8.6 MB/s eta 0:00:09
   -------------------- ------------------- 75.2/150.0 MB 8.5 MB/s eta 0:00:09
   -------------------- ------------------- 76.8/150.0 MB 8.5 MB/s eta 0:00:09
   -------------------- ------------------- 78.4/150.0 MB 8.4 MB/s eta 0:00:09
   --------------------- ------------------ 79.7/150.0 MB 8.4 MB/s eta 0:00:09
   --------------------- ------------------ 81.5/150.0 MB 8.4 MB/s eta 0:00:09
   ---------------------- ----------------- 83.1/150.0 MB 8.4 MB/s eta 0:00:08
   ---------------------- ----------------- 84.9/150.0 MB 8.4 MB/s eta 0:00:08
   ----------------------- ---------------- 86.8/150.0 MB 8.4 MB/s eta 0:00:08
   ----------------------- ---------------- 88.6/150.0 MB 8.4 MB/s eta 0:00:08
   ------------------------ --------------- 90.7/150.0 MB 8.4 MB/s eta 0:00:08
   ------------------------ --------------- 92.8/150.0 MB 8.4 MB/s eta 0:00:07
   ------------------------- -------------- 94.6/150.0 MB 8.4 MB/s eta 0:00:07
   ------------------------- -------------- 96.5/150.0 MB 8.4 MB/s eta 0:00:07
   -------------------------- ------------- 98.0/150.0 MB 8.4 MB/s eta 0:00:07
   -------------------------- ------------- 99.4/150.0 MB 8.4 MB/s eta 0:00:07
   -------------------------- ------------- 100.9/150.0 MB 8.4 MB/s eta 0:00:06
   --------------------------- ------------ 103.0/150.0 MB 8.4 MB/s eta 0:00:06
   --------------------------- ------------ 104.6/150.0 MB 8.4 MB/s eta 0:00:06
   ---------------------------- ----------- 106.4/150.0 MB 8.4 MB/s eta 0:00:06
   ---------------------------- ----------- 108.5/150.0 MB 8.4 MB/s eta 0:00:05
   ----------------------------- ---------- 110.6/150.0 MB 8.4 MB/s eta 0:00:05
   ------------------------------ --------- 112.7/150.0 MB 8.4 MB/s eta 0:00:05
   ------------------------------ --------- 114.8/150.0 MB 8.4 MB/s eta 0:00:05
   ------------------------------- -------- 116.7/150.0 MB 8.4 MB/s eta 0:00:04
   ------------------------------- -------- 118.8/150.0 MB 8.5 MB/s eta 0:00:04
   -------------------------------- ------- 120.8/150.0 MB 8.5 MB/s eta 0:00:04
   -------------------------------- ------- 123.5/150.0 MB 8.5 MB/s eta 0:00:04
   --------------------------------- ------ 125.6/150.0 MB 8.6 MB/s eta 0:00:03
   ---------------------------------- ----- 127.7/150.0 MB 8.6 MB/s eta 0:00:03
   ---------------------------------- ----- 129.5/150.0 MB 8.6 MB/s eta 0:00:03
   ----------------------------------- ---- 131.9/150.0 MB 8.6 MB/s eta 0:00:03
   ----------------------------------- ---- 134.5/150.0 MB 8.6 MB/s eta 0:00:02
   ------------------------------------ --- 136.8/150.0 MB 8.7 MB/s eta 0:00:02
   ------------------------------------ --- 138.4/150.0 MB 8.7 MB/s eta 0:00:02
   ------------------------------------- -- 140.0/150.0 MB 8.6 MB/s eta 0:00:02
   ------------------------------------- -- 141.3/150.0 MB 8.6 MB/s eta 0:00:02
   -------------------------------------- - 142.6/150.0 MB 8.6 MB/s eta 0:00:01
   -------------------------------------- - 144.2/150.0 MB 8.6 MB/s eta 0:00:01
   -------------------------------------- - 145.2/150.0 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------  146.3/150.0 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------  147.3/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  148.6/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  149.9/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  149.9/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  149.9/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  149.9/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  149.9/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  149.9/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  149.9/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  149.9/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  149.9/150.0 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 150.0/150.0 MB 7.6 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.0.2

In [24]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [25]:
models = {
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'XG Boost': XGBClassifier()
}

In [26]:
def evaluate_model(true, predict):
    accuracy = accuracy_score(true, predict)
    f1 = f1_score(true, predict)
    precision = precision_score(true, predict)
    recall = recall_score(true, predict)
    roc= roc_auc_score(true, predict)

    return accuracy, f1, precision, recall, roc

In [27]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train)

    # make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # calculate score
    train_accuracy, train_f1, train_precision, train_recall, train_roc = evaluate_model(y_train, y_train_pred)
    test_accuracy, test_f1, test_precision, test_recall, test_roc = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])

    # print the scores
    print('Model Performance of Training Data')
    print(f'Accuracy: {train_accuracy:.4f}')
    print(f'F1 Score: {train_f1:.4f}')
    print(f'Precision: {train_precision:.4f}')
    print(f'Recall Score: {train_recall:.4f}')
    print(f'ROC Score: {train_roc:.4f}')

    print('Model Performance of Test Data')
    print(f'Accuracy: {test_accuracy:.4f}')
    print(f'F1 Score: {test_f1:.4f}')
    print(f'Precision: {test_precision:.4f}')
    print(f'Recall Score: {test_recall:.4f}')
    print(f'ROC Score: {test_roc:.4f}')

    print('*'*30)

Random Forest
Model Performance of Training Data
Accuracy: 1.0000
F1 Score: 1.0000
Precision: 1.0000
Recall Score: 1.0000
ROC Score: 1.0000
Model Performance of Test Data
Accuracy: 0.9305
F1 Score: 0.7901
Precision: 0.9624
Recall Score: 0.6702
ROC Score: 0.8319
******************************
Gradient Boosting
Model Performance of Training Data
Accuracy: 0.8939
F1 Score: 0.6382
Precision: 0.8756
Recall Score: 0.5021
ROC Score: 0.7429
Model Performance of Test Data
Accuracy: 0.8589
F1 Score: 0.5208
Precision: 0.7732
Recall Score: 0.3927
ROC Score: 0.6824
******************************
AdaBoost
Model Performance of Training Data
Accuracy: 0.8478
F1 Score: 0.3847
Precision: 0.7815
Recall Score: 0.2551
ROC Score: 0.6194
Model Performance of Test Data
Accuracy: 0.8354
F1 Score: 0.3586
Precision: 0.7500
Recall Score: 0.2356
ROC Score: 0.6083
******************************
Decision Tree
Model Performance of Training Data
Accuracy: 1.0000
F1 Score: 1.0000
Precision: 1.0000
Recall Score: 1.0000
ROC Score: 1.0000
Model Performance of Test Data
Accuracy: 0.9151
F1 Score: 0.7751
Precision: 0.8034
Recall Score: 0.7487
ROC Score: 0.8521
******************************
XG Boost
Model Performance of Training Data
Accuracy: 0.9992
F1 Score: 0.9979
Precision: 1.0000
Recall Score: 0.9959
ROC Score: 0.9979
Model Performance of Test Data
Accuracy: 0.9356
F1 Score: 0.8108
Precision: 0.9507
Recall Score: 0.7068
ROC Score: 0.8490
******************************

In [28]:
rf_params = {
    "max_depth": [5, 8, 15, None, 10],
    "max_features": [5, 7, "auto", 8],
    "min_samples_split": [2, 8, 15, 20],
    "n_estimators": [100, 200, 500, 1000]
}

xgb_params = {
    "learning_rate": [0.1, 0.01],
    "max_depth": [5, 8, 12, 20, 30],
    "n_estimators": [100, 200, 300],
    "colsample_bytree": [0.5, 0.8, 1, 0.3, 0.4]
}

In [29]:
randomcv_models = [
    ('Random Forest', RandomForestClassifier(), rf_params),
    ('XGBoost', XGBClassifier(), xgb_params)
]

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model, param_distributions=params, n_iter=100, cv=3, verbose=2, n_jobs=-1)
    random.fit(x_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f'Best parameter for {model_name}')
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits

d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
66 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
17 fits failed with the following error:
Traceback (most recent call last):
  File "d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
49 fits failed with the following error:
Traceback (most recent call last):
  File "d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
d:\DS, ML, DL, NLP\Machine Learning\venv\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.84501434 0.87084371 0.87570272 0.83529534        nan
 0.8519199         nan 0.87314629 0.86368409 0.84450191 0.86368448
 0.87161137 0.83989912 0.89130479        nan 0.88925941 0.87493644
 0.88695683 0.87774948 0.87672639 0.84526996 0.88797992        nan
 0.84373583 0.84117802 0.86803185 0.86598529 0.86854212 0.87161176
 0.86445057        nan 0.8841438         nan 0.86163773        nan
        nan        nan 0.86572908 0.86445116 0.86777525 0.87237902
 0.91406747        nan 0.86828728 0.86112628        nan 0.91355661
        nan 0.91764796 0.8831213  0.86291604 0.85652231 0.89079315
 0.86317225 0.84552578 0.84552519        nan        nan 0.84475812
 0.87314648 0.84399106 0.89309416 0.84475832 0.88542329 0.84117743
        nan 0.87493624 0.89181761 0.86624033 0.91483453 0.85831324
 0.88516708 0.87033305        nan 0.8890028  0.83452788 0.86010222
 0.86445018 0.86010281 0.86751962        nan 0.88951464 0.87365734
 0.86342748 0.89053733 0.89028132 0.90664987 0.87135535 0.883887
 0.83529514 0.86777485        nan        nan 0.88030709        nan
 0.8649628  0.869565   0.9133004         nan]
  warnings.warn(

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Best parameter for Random Forest
{'n_estimators': 100, 'min_samples_split': 2, 'max_features': 8, 'max_depth': None}
Best parameter for XGBoost
{'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.1, 'colsample_bytree': 0.8}

In [32]:
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, min_samples_split=2, max_features=8, max_depth=None),
    'XGBoost': XGBClassifier(n_estimators=300, max_depth=8, learning_rate=0.1, colsample_bytree=0.8),
}

In [33]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train)

    # make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # calculate score
    train_accuracy, train_f1, train_precision, train_recall, train_roc = evaluate_model(y_train, y_train_pred)
    test_accuracy, test_f1, test_precision, test_recall, test_roc = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])

    # print the scores
    print('Model Performance of Training Data')
    print(f'Accuracy: {train_accuracy:.4f}')
    print(f'F1 Score: {train_f1:.4f}')
    print(f'Precision: {train_precision:.4f}')
    print(f'Recall Score: {train_recall:.4f}')
    print(f'ROC Score: {train_roc:.4f}')

    print('Model Performance of Test Data')
    print(f'Accuracy: {test_accuracy:.4f}')
    print(f'F1 Score: {test_f1:.4f}')
    print(f'Precision: {test_precision:.4f}')
    print(f'Recall Score: {test_recall:.4f}')
    print(f'ROC Score: {test_roc:.4f}')

    print('*'*30)

Random Forest
Model Performance of Training Data
Accuracy: 1.0000
F1 Score: 1.0000
Precision: 1.0000
Recall Score: 1.0000
ROC Score: 1.0000
Model Performance of Test Data
Accuracy: 0.9376
F1 Score: 0.8157
Precision: 0.9643
Recall Score: 0.7068
ROC Score: 0.8502
******************************
XGBoost
Model Performance of Training Data
Accuracy: 1.0000
F1 Score: 1.0000
Precision: 1.0000
Recall Score: 1.0000
ROC Score: 1.0000
Model Performance of Test Data
Accuracy: 0.9540
F1 Score: 0.8703
Precision: 0.9679
Recall Score: 0.7906
ROC Score: 0.8921
******************************