In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
df = pd.read_csv('IndianHouses.csv')

In [4]:
df.head()

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0

In [5]:
df.isnull().sum()

Area             0
BHK              0
Bathroom         2
Furnishing       5
Locality         0
Parking         33
Price            0
Status           0
Transaction      0
Type             5
Per_Sqft       241
dtype: int64

In [6]:
df.shape

(1259, 11)

In [9]:
df = df.dropna()

In [10]:
df.shape

(1005, 11)

In [11]:
df = df.drop(['Locality', 'Per_Sqft'], axis=1)

In [12]:
df.head()

,Area,BHK,Bathroom,Furnishing,Parking,Price,Status,Transaction,Type
1,750.0,2,2.0,Semi-Furnished,1.0,5000000,Ready_to_move,New_Property,Apartment
2,950.0,2,2.0,Furnished,1.0,15500000,Ready_to_move,Resale,Apartment
3,600.0,2,2.0,Semi-Furnished,1.0,4200000,Ready_to_move,Resale,Builder_Floor
4,650.0,2,2.0,Semi-Furnished,1.0,6200000,Ready_to_move,New_Property,Builder_Floor
5,1300.0,4,3.0,Semi-Furnished,1.0,15500000,Ready_to_move,New_Property,Builder_Floor

In [14]:
print(df['Furnishing'].value_counts())
print(df['Status'].value_counts())
print(df['Transaction'].value_counts())
print(df['Type'].value_counts())

Furnishing
Semi-Furnished    563
Unfurnished       301
Furnished         141
Name: count, dtype: int64
Status
Ready_to_move    940
Almost_ready      65
Name: count, dtype: int64
Transaction
Resale          603
New_Property    402
Name: count, dtype: int64
Type
Builder_Floor    550
Apartment        455
Name: count, dtype: int64

In [15]:
df.head()

,Area,BHK,Bathroom,Furnishing,Parking,Price,Status,Transaction,Type
1,750.0,2,2.0,Semi-Furnished,1.0,5000000,Ready_to_move,New_Property,Apartment
2,950.0,2,2.0,Furnished,1.0,15500000,Ready_to_move,Resale,Apartment
3,600.0,2,2.0,Semi-Furnished,1.0,4200000,Ready_to_move,Resale,Builder_Floor
4,650.0,2,2.0,Semi-Furnished,1.0,6200000,Ready_to_move,New_Property,Builder_Floor
5,1300.0,4,3.0,Semi-Furnished,1.0,15500000,Ready_to_move,New_Property,Builder_Floor

In [16]:
df['Furnishing'] = df['Furnishing'].str.strip().str.title().replace({
    'Furnished': 1,
    'Unfurnished': 2,
    'Semi-Furnished': 3
})

C:\Users\om_da\AppData\Local\Temp\ipykernel_8684\1751956267.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Furnishing'] = df['Furnishing'].str.strip().str.title().replace({

In [25]:
df['Status'] = df['Status'].str.strip().str.title().replace({
    'Ready_To_Move': 1,
    'Almost_Ready': 2,
})

C:\Users\om_da\AppData\Local\Temp\ipykernel_8684\996243747.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Status'] = df['Status'].str.strip().str.title().replace({

In [18]:
df['Transaction'] = df['Transaction'].str.strip().str.title().replace({
    'Resale': 1,
    'New_Property': 2,
})

C:\Users\om_da\AppData\Local\Temp\ipykernel_8684\318507347.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Transaction'] = df['Transaction'].str.strip().str.title().replace({

In [19]:
df['Type'] = df['Type'].str.strip().str.title().replace({
    'Builder_Floor': 1,
    'Apartment': 2,
})

C:\Users\om_da\AppData\Local\Temp\ipykernel_8684\2892658439.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Type'] = df['Type'].str.strip().str.title().replace({

In [26]:
df.head()

,Area,BHK,Bathroom,Furnishing,Parking,Price,Status,Transaction,Type
1,750.0,2,2.0,3,1.0,5000000,1,2,2
2,950.0,2,2.0,1,1.0,15500000,1,1,2
3,600.0,2,2.0,3,1.0,4200000,1,1,1
4,650.0,2,2.0,3,1.0,6200000,1,2,1
5,1300.0,4,3.0,3,1.0,15500000,1,2,1

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1005 entries, 1 to 1258
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Area         1005 non-null   float64
 1   BHK          1005 non-null   int64
 2   Bathroom     1005 non-null   float64
 3   Furnishing   1005 non-null   int64
 4   Parking      1005 non-null   float64
 5   Price        1005 non-null   int64
 6   Status       1005 non-null   int64
 7   Transaction  1005 non-null   int64
 8   Type         1005 non-null   int64
dtypes: float64(3), int64(6)
memory usage: 78.5 KB

In [29]:
# dependant and independant feature

x = df[['Area', 'BHK', 'Bathroom', 'Furnishing', 'Parking', 'Status', 'Transaction', 'Type']]
y = df['Price']

In [30]:
x.head()

     Area  BHK  Bathroom  Furnishing  Parking  Status  Transaction  Type
1   750.0    2       2.0           3      1.0       1            2     2
2   950.0    2       2.0           1      1.0       1            1     2
3   600.0    2       2.0           3      1.0       1            1     1
4   650.0    2       2.0           3      1.0       1            2     1
5  1300.0    4       3.0           3      1.0       1            2     1

In [31]:
y.head()

1     5000000
2    15500000
3     4200000
4     6200000
5    15500000
Name: Price, dtype: int64

In [33]:
# train test split

from sklearn.model_selection import train_test_split

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 42)

In [37]:
# train the model

from sklearn.linear_model import LinearRegression

In [38]:
linear = LinearRegression(n_jobs=-1)

In [39]:
linear.fit(x_train, y_train)

LinearRegression(n_jobs=-1)

In [46]:
y_pred = linear.predict(x_test)

In [51]:
# performance metrics

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [52]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(mse)
print(mae)
print(rmse)
print(r2)

498650984893570.56
11511190.677508442
22330494.506247964
0.5442661484437524